<<<<<<< HEAD
# Generated by Django 5.0.9 on 2024-10-22 04:36
=======
# Generated by Django 5.0.9 on 2024-10-22 01:48
>>>>>>> 1e04cd6 (ubuntu)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/%Y/%m/%d', verbose_name='Главное фото'),
        ),
    ]
